ENH: Improve CI.
InsightSoftwareConsortium/ITKRobustPredicate pull request #1
Opened 2018-11-10 21:11 UTC by jhlegarreta

Improve the module's CI:
- Add Circle, Travis and AppVeyor CI configuration `*.yml` files.
- Add the `CTestConfig.cmake` file to submit builds to the **Insight**
  project in the **open.cdash.org** dashboard.
- Add the Python setup `setup.py` file
- Add the Python wrapping files.

2018-11-10 21:13 UTC, jhlegarreta commented
Not sure whether this requires any wrapping/whether it makes sense here: I added an empty `CMakeLists.txt` file. @phcerdan @thewtex please comment on this. Thanks !

2018-11-11 03:05 UTC, thewtex commented
Thanks, @jhlegarreta 

We can skip wrapping for this module.

2018-11-11 13:51 UTC, jhlegarreta commented
Done in c189d20.

2018-11-11 14:20 UTC, thewtex requested changes

2018-11-11 14:20 UTC, thewtex commented on .circleci/config.yml
> +  package:
We can remove this section, since we are not building a package.

2018-11-11 14:20 UTC, thewtex commented on .travis.yml
> +sudo: true
We can remove this file, since we are not building a package.

2018-11-11 14:20 UTC, thewtex commented on appveyor.yml
> +branches:
We can remove this file, since we are not building a package.

2018-11-11 14:20 UTC, thewtex commented on setup.py
> +# -*- coding: utf-8 -*-
We can remove this file, since we are not building a package.

2018-11-11 17:18 UTC, jhlegarreta commented on .circleci/config.yml
> +  package:
Done in cf1093a. Thanks Matt.

2018-11-11 17:18 UTC, jhlegarreta commented on .travis.yml
> +sudo: true
Done in cf1093a. Thanks Matt.

2018-11-11 17:18 UTC, jhlegarreta commented on setup.py
> +# -*- coding: utf-8 -*-
Done in cf1093a. Thanks Matt.

2018-11-11 18:43 UTC, thewtex reviewed
Thanks for the updates, @jhlegarreta 

I disabled the TravisCI and Appveyor builds.

A `KWStyleOverwrite.txt` could be added to address the current test failure.

2018-11-11 18:43 UTC, thewtex requested changes

2018-11-11 18:43 UTC, thewtex commented on .circleci/config.yml
> +        - package
The reference to the `package` job can be removed.

2018-11-12 03:42 UTC, jhlegarreta commented on .circleci/config.yml
> +        - package
Done in ab5b15e.

2018-11-12 03:47 UTC, jhlegarreta commented
File `ITKKWStyleOverwrite.txt` added in #5.

2018-11-12 04:26 UTC, thewtex approved these changes

2018-11-12 04:26 UTC, merged